# Generated by Django 2.1.2 on 2018-10-15 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181014_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('subject', models.TextField()),
                ('details', models.TextField()),
                ('priority', models.TextField()),
                ('affected_system', models.TextField()),
                ('module', models.TextField()),
                ('date', models.TextField(null=True)),
                ('attached_file', models.FileField(null=True, upload_to='')),
                ('assigned_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technician', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
