# Generated by Django 2.1.2 on 2018-10-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181017_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='es_tecnico',
            field=models.BooleanField(default=False),
        ),
    ]
