# Generated by Django 2.1.2 on 2018-10-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181018_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='assigned_technician',
            new_name='assignedTechnician',
        ),
    ]
