# Generated by Django 2.1.2 on 2018-10-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181020_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isTechnician',
            field=models.BooleanField(default=True),
        ),
    ]
