# Generated by Django 2.1.2 on 2018-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181021_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isTechnician',
            field=models.BooleanField(default=False),
        ),
    ]
