# Generated by Django 2.1.2 on 2018-10-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181022_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='api.Type'),
        ),
    ]
