# Generated by Django 2.1.2 on 2018-10-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20181026_1944'),
        ('api', '0026_merge_20181023_1244'),
    ]

    operations = [
    ]
