# Generated by Django 2.1.2 on 2018-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_tecnico',
            field=models.BooleanField(default=True),
        ),
    ]
