# Generated by Django 2.1.2 on 2018-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_es_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='es_tecnico',
            field=models.BooleanField(default=False),
        ),
    ]
