# Generated by Django 2.1.2 on 2018-10-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181017_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='es_tecnico',
            field=models.BooleanField(default=True),
        ),
    ]
