# Generated by Django 2.1.2 on 2018-10-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181017_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='es_tecnico',
            new_name='is_technician',
        ),
    ]
