# Generated by Django 2.1.2 on 2018-10-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181018_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
