# Generated by Django 2.1.2 on 2018-10-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181018_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
