# Generated by Django 2.1.2 on 2018-10-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181020_2353'),
        ('api', '0023_auto_20181021_2050'),
    ]

    operations = [
    ]
