# Generated by Django 2.1.2 on 2018-10-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181022_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='name',
            new_name='sname',
        ),
    ]
