# Generated by Django 2.1.2 on 2018-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20181021_2352'),
        ('api', '0025_auto_20181022_1505'),
    ]

    operations = [
    ]
