# Generated by Django 2.1.2 on 2018-10-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181026_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='sname',
            new_name='name',
        ),
    ]
